//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap accept_ico {
            get {
                object obj = ResourceManager.GetObject("accept_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak :). Najlepiej będzie jeżeli poprosisz kogoś o pomoc :).
        /// </summary>
        internal static string BaseScreenGenericErrorMsg {
            get {
                return ResourceManager.GetString("BaseScreenGenericErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, wygląda na to, że kamera nie jest podłączona :).
        /// </summary>
        internal static string CameraErrorDeviceNotConnectedMsg {
            get {
                return ResourceManager.GetString("CameraErrorDeviceNotConnectedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wysąpił błąd, najlepiej będzie jeżeli poprosisz kogoś o pomoc :)..
        /// </summary>
        internal static string CameraErrorGenericMsg {
            get {
                return ResourceManager.GetString("CameraErrorGenericMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zastosuj.
        /// </summary>
        internal static string ChromaKeySettingsScreenBaseApplayBtnTxt {
            get {
                return ResourceManager.GetString("ChromaKeySettingsScreenBaseApplayBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string ChromaKeySettingsScreenBaseCancelBtnTxt {
            get {
                return ResourceManager.GetString("ChromaKeySettingsScreenBaseCancelBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap down_ico {
            get {
                object obj = ResourceManager.GetObject("down_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ErrorScreenReturnBtnText {
            get {
                return ResourceManager.GetString("ErrorScreenReturnBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Nie mogę zainicjalizowac biblioteki PBVL, a konkretnie = {0}&quot;.
        /// </summary>
        internal static string LiveViewSettingsScreenCanNotInitPBVLLibErr {
            get {
                return ResourceManager.GetString("LiveViewSettingsScreenCanNotInitPBVLLibErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrób zdjęcie.
        /// </summary>
        internal static string LiveViewSettingsScreenTakePhotoBtnTxt {
            get {
                return ResourceManager.GetString("LiveViewSettingsScreenTakePhotoBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_screen_bg {
            get {
                object obj = ResourceManager.GetObject("main_screen_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_screen_bg_new_year {
            get {
                object obj = ResourceManager.GetObject("main_screen_bg_new_year", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap main_screen_bg_weedings {
            get {
                object obj = ResourceManager.GetObject("main_screen_bg_weedings", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.foto.starakaszarnia.pl.
        /// </summary>
        internal static string MainScrWwwTxt {
            get {
                return ResourceManager.GetString("MainScrWwwTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm wystąpił jakiś bląd podczas przetwarzania zdjęcia. Skontaktuj się z producentem :P.
        /// </summary>
        internal static string PhotoSettingsScrrenErrorProcessImgTxt {
            get {
                return ResourceManager.GetString("PhotoSettingsScrrenErrorProcessImgTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap power_off_ico {
            get {
                object obj = ResourceManager.GetObject("power_off_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap print_screen_loading {
            get {
                object obj = ResourceManager.GetObject("print_screen_loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień tusz i papier w drukarce.
        /// </summary>
        internal static string PrinterInfoScreenNoInk {
            get {
                return ResourceManager.GetString("PrinterInfoScreenNoInk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wymień papier w drukarce.
        /// </summary>
        internal static string PrinterInfoScreenNoPaper {
            get {
                return ResourceManager.GetString("PrinterInfoScreenNoPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string PrintInfoScreenBtnOkTxt {
            get {
                return ResourceManager.GetString("PrintInfoScreenBtnOkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printing_screen_bg {
            get {
                object obj = ResourceManager.GetObject("printing_screen_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wystąpił błąd podczas drukowania zdjęcia. Spróbuj ponownie :).
        /// </summary>
        internal static string PrintScreenPrintErrorMsg {
            get {
                return ResourceManager.GetString("PrintScreenPrintErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drukuje . . . .
        /// </summary>
        internal static string PrintScreenPrintingTxt {
            get {
                return ResourceManager.GetString("PrintScreenPrintingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przetwarzam zdjęcia . . . .
        /// </summary>
        internal static string PrintScreenProcessingImagesTxt {
            get {
                return ResourceManager.GetString("PrintScreenProcessingImagesTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_bg_screen_cancel_ico {
            get {
                object obj = ResourceManager.GetObject("set_bg_screen_cancel_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_bg_screen_next_ico {
            get {
                object obj = ResourceManager.GetObject("set_bg_screen_next_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap set_bg_screen_prev_ico {
            get {
                object obj = ResourceManager.GetObject("set_bg_screen_prev_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        internal static string SetBgScrCancelBtnTxt {
            get {
                return ResourceManager.GetString("SetBgScrCancelBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następny.
        /// </summary>
        internal static string SetBgScrNextBtnTxt {
            get {
                return ResourceManager.GetString("SetBgScrNextBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona {0} z {1}.
        /// </summary>
        internal static string SetbgScrPageTxt {
            get {
                return ResourceManager.GetString("SetbgScrPageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzedni.
        /// </summary>
        internal static string SetBgScrPrevBtnTxt {
            get {
                return ResourceManager.GetString("SetBgScrPrevBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autor: Stara Kaszarnia (R) 2014.
        /// </summary>
        internal static string SettingsScreenAboutAuthor {
            get {
                return ResourceManager.GetString("SettingsScreenAboutAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt: restauracja@arbi.pl.
        /// </summary>
        internal static string SettingsScreenAboutContact {
            get {
                return ResourceManager.GetString("SettingsScreenAboutContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wersja oprogramowania: 1.0.1.
        /// </summary>
        internal static string SettingsScreenAboutVersion {
            get {
                return ResourceManager.GetString("SettingsScreenAboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw wartości HSV dla LiveView (podgląd na żywo).
        /// </summary>
        internal static string SettingsScreenLiveViewSettingsBtnText {
            get {
                return ResourceManager.GetString("SettingsScreenLiveViewSettingsBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfiguracja.
        /// </summary>
        internal static string SettingsScreenMainTxt {
            get {
                return ResourceManager.GetString("SettingsScreenMainTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw wartości HSV dla zdjęcia.
        /// </summary>
        internal static string SettingsScreenPhotoSettingsBtnText {
            get {
                return ResourceManager.GetString("SettingsScreenPhotoSettingsBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_photo_screen_bg {
            get {
                object obj = ResourceManager.GetObject("take_photo_screen_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_photo_screen_bg_btn_ico {
            get {
                object obj = ResourceManager.GetObject("take_photo_screen_bg_btn_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_photo_screen_col_ef_btn_ico {
            get {
                object obj = ResourceManager.GetObject("take_photo_screen_col_ef_btn_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_photo_screen_fg_btn_ico {
            get {
                object obj = ResourceManager.GetObject("take_photo_screen_fg_btn_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap take_photo_screen_tak_ph_btn_ico {
            get {
                object obj = ResourceManager.GetObject("take_photo_screen_tak_ph_btn_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tła.
        /// </summary>
        internal static string TakePhotoScrBgBtnTxt {
            get {
                return ResourceManager.GetString("TakePhotoScrBgBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efekty.
        /// </summary>
        internal static string TakePhotoScrColEfBtnTxt {
            get {
                return ResourceManager.GetString("TakePhotoScrColEfBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tła przednie.
        /// </summary>
        internal static string TakePhotoScrFgBtnTxt {
            get {
                return ResourceManager.GetString("TakePhotoScrFgBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrób zdjęcie.
        /// </summary>
        internal static string TakePhotoScrTakePhotoBtnTxt {
            get {
                return ResourceManager.GetString("TakePhotoScrTakePhotoBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap up_ico {
            get {
                object obj = ResourceManager.GetObject("up_ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
